version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
# test
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          - v2-dependencies-

      - run: yarn install --frozen-lock

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn check-license-headers
      - run: yarn lint
      - run: yarn test